version: "3.10"

services:
  app:
    build: .
    volumes:
      - .:/core
      - ./static:/app/static
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    ports:
    - "8000:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn keu.wsgi:application -w 4 -b 0.0.0.0:8000"