# Generated by Django 4.1.7 on 2023-03-29 00:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news_alter_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
