# Generated by Django 4.2.4 on 2025-03-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_programcategory_program_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='head_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.headcategory'),
        ),
    ]
