# Generated by Django 5.1.7 on 2025-03-18 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_headcategory_category_head_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=123)),
            ],
        ),
        migrations.AddField(
            model_name="aboutkeu",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about_pages",
                to="app.aboutcategory",
            ),
        ),
    ]
